var myBooks = [
  {"Ad title":"Galaxy S10 Official TVC: The Next Generation Galaxy",
   "Ad link":"https://www.youtube.com/watch?v=sbQZ0Mrpp80",
   "Music name":"Get Dat",
   "Music link":"https://www.youtube.com/watch?v=goPMIeVHbOA",
   "Artist":"Rayelle"},
  {"Ad title":"Galaxy Fold - Unveiling",
   "Ad link":"https://www.youtube.com/watch?v=oJYb1LqE90w",
   "Music name":"Pure Imagination",
   "Music link":"https://www.youtube.com/watch?v=iUUWfKYjFDs",
   "Artist":"Joanna Wang"},
  {"Ad title":"Galaxy S10 - Unveiling",
   "Ad link":"https://www.youtube.com/watch?v=IWVXt2E0cmA",
   "Music name":"Unstoppable Now",
   "Artist":"The Phantoms",
   "Music link":"https://www.youtube.com/watch?v=ppkXdOJkqkU"},
  {"Ad title":"Galaxy S10 5G: Everything You Love, HyperFast",
   "Ad link":"https://www.youtube.com/watch?v=Za_F_Yn2VXA",
   "Music name":"HOLUP!",
   "Artist":"Bobby (iKON)",
   "Music link":"https://www.youtube.com/watch?v=-Tap_zZdkYA"},
  {"Ad title":"Galaxy Note10 Official TVC: Next-level power",
   "Ad link":"https://www.youtube.com/watch?v=4_Y995u6HFw",
   "Music name":"I AM",
   "Artist":"Club Yoko",
   "Music link":"https://www.youtube.com/watch?v=qcAb0XH5Pdg"}
]